### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by clubdesarrolladores** [egulias/SecurityDebugCommandBundle#5]
Hi, i got this error:

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  The service "egulias.security_listeners_debug" has a dependency on a non-existent service "sensio_framework_extra.security.listener".

**Comment by egulias** [comment]
Hi @clubdesarrolladores 
Which version of Symfony are you using? It could be that latest Symfony had removed this service.

**Comment by patrickallaert** [comment]
I had the same issue, but that was not the version of Symfony that was the culprit.

I had:

```
sensio_framework_extra:
    security:
        annotations: false
```

which obviously prevented `sensio_framework_extra.security.listener` to be registered.

Turning that config to `true` resolved the issue.
